/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package parser.sql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMI = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int TIMES = 8;
  /** RegularExpression Id. */
  int DIV = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int AND = 11;
  /** RegularExpression Id. */
  int OR = 12;
  /** RegularExpression Id. */
  int GT = 13;
  /** RegularExpression Id. */
  int LT = 14;
  /** RegularExpression Id. */
  int EQ = 15;
  /** RegularExpression Id. */
  int GE = 16;
  /** RegularExpression Id. */
  int LE = 17;
  /** RegularExpression Id. */
  int NUMBER = 18;
  /** RegularExpression Id. */
  int DIGITS = 19;
  /** RegularExpression Id. */
  int CREATE = 20;
  /** RegularExpression Id. */
  int DROP = 21;
  /** RegularExpression Id. */
  int UPDATE = 22;
  /** RegularExpression Id. */
  int DELETE = 23;
  /** RegularExpression Id. */
  int SELECT = 24;
  /** RegularExpression Id. */
  int INSERT = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\";\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
    "\"&\"",
    "\"|\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "<NUMBER>",
    "<DIGITS>",
    "\"CREATE\"",
    "\"DROP\"",
    "\"UPDATE\"",
    "\"DELETE\"",
    "\"SELECT\"",
    "\"INSERT\"",
  };

}
